pipeline {
  agent {
    dockerContainer { image 'kipgeoffry/myjenkinsagent:python' }
  }
  stages {
    stage('Check python') {
      steps {
        sh 'python --version'
      }
    }
     stage('Check hostname') {
          steps {
            sh 'cat /etc/hostname'
          }
        }
  }
}
