pipeline {
  agent {
    dockerContainer { image 'node:18-alpine' }
  }
  stages {
    stage('Check python') {
      steps {
        sh 'node --version'
      }
    }
     stage('Check hostname') {
          steps {
            sh 'cat /etc/hostname'
          }
        }
  }
}
